import { lazy, type LazyExoticComponent, type ComponentType } from "react";

// Route manifest. Each entry maps a route name to a dynamic import of the
// corresponding fixture component. Playwright navigates to `#/<name>`.
export const routes: Record<string, LazyExoticComponent<ComponentType>> = {
  Dialog: lazy(() => import("./routes/Dialog")),
  DrawerV2: lazy(() => import("./routes/DrawerV2")),
  Sheet: lazy(() => import("./routes/Sheet")),
  Popover: lazy(() => import("./routes/Popover")),
  Tooltip: lazy(() => import("./routes/Tooltip")),
  HoverCard: lazy(() => import("./routes/HoverCard")),
  Menu: lazy(() => import("./routes/Menu")),
  MenuBar: lazy(() => import("./routes/MenuBar")),
  ContextMenu: lazy(() => import("./routes/ContextMenu")),
  Popconfirm: lazy(() => import("./routes/Popconfirm")),
  Spotlight: lazy(() => import("./routes/Spotlight")),
  CommandPalette: lazy(() => import("./routes/CommandPalette")),
  ToastSystem: lazy(() => import("./routes/ToastSystem")),
  Tabs: lazy(() => import("./routes/Tabs")),
  Accordion: lazy(() => import("./routes/Accordion")),
  Collapsible: lazy(() => import("./routes/Collapsible")),
  Toolbar: lazy(() => import("./routes/Toolbar")),
  Calendar: lazy(() => import("./routes/Calendar")),
  ColorPicker: lazy(() => import("./routes/ColorPicker")),
  Combobox: lazy(() => import("./routes/Combobox")),
  MultiSelect: lazy(() => import("./routes/MultiSelect")),
  NumberStepper: lazy(() => import("./routes/NumberStepper")),
  Slider: lazy(() => import("./routes/Slider")),
  DatePicker: lazy(() => import("./routes/DatePicker")),
  DateRangePicker: lazy(() => import("./routes/DateRangePicker")),
  RadioGroup: lazy(() => import("./routes/RadioGroup")),
  DataGrid: lazy(() => import("./routes/DataGrid")),
  DataGridLarge: lazy(() => import("./routes/DataGridLarge")),
  TreeView: lazy(() => import("./routes/TreeView")),
  Sortable: lazy(() => import("./routes/Sortable")),
  Pagination: lazy(() => import("./routes/Pagination")),
  Stepper: lazy(() => import("./routes/Stepper")),
  Wizard: lazy(() => import("./routes/Wizard")),
  Carousel: lazy(() => import("./routes/Carousel")),
  ScrollArea: lazy(() => import("./routes/ScrollArea")),
  Resizable: lazy(() => import("./routes/Resizable")),
  CopyButton: lazy(() => import("./routes/CopyButton")),
  SignaturePad: lazy(() => import("./routes/SignaturePad")),
  ImageCropper: lazy(() => import("./routes/ImageCropper")),
  FileUpload: lazy(() => import("./routes/FileUpload")),
  DisplaySweep: lazy(() => import("./routes/DisplaySweep")),
  NestedOverlays: lazy(() => import("./routes/NestedOverlays")),
  FocusChain: lazy(() => import("./routes/FocusChain")),
  ScrollLockStack: lazy(() => import("./routes/ScrollLockStack")),
  ThemeSwitchLive: lazy(() => import("./routes/ThemeSwitchLive")),
};

export const routeNames = Object.keys(routes);
