// Phase 14 — Icon barrel

export { Icon } from "./Icon";
export type { IconProps, IconSize } from "./Icon";

export { IconButton, IconGroup } from "./IconButton";
export type {
  IconButtonProps,
  IconButtonVariant,
  IconButtonSize,
  IconGroupProps,
} from "./IconButton";

export { adaptIcon } from "./adapters";

export {
  PlusIcon,
  MinusIcon,
  CheckIcon,
  XIcon,
  EditIcon,
  TrashIcon,
  CopyIcon,
  DownloadIcon,
  UploadIcon,
  RefreshIcon,
  SaveIcon,
  ShareIcon,
  SendIcon,
  BookmarkIcon,
  PinIcon,
  ChevronUpIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  HomeIcon,
  ExternalLinkIcon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  MenuIcon,
  FileIcon,
  FileTextIcon,
  FolderIcon,
  FolderOpenIcon,
  BoldIcon,
  ItalicIcon,
  UnderlineIcon,
  CodeIcon,
  QuoteIcon,
  LinkIcon,
  InfoIcon,
  WarningIcon,
  ErrorIcon,
  SuccessIcon,
  QuestionIcon,
  SpinnerIcon,
  CircleIcon,
  SquareIcon,
  StarIcon,
  HeartIcon,
  SettingsIcon,
  UserIcon,
  UsersIcon,
  LockIcon,
  UnlockIcon,
  EyeIcon,
  EyeOffIcon,
  SearchIcon,
  FilterIcon,
  SortIcon,
  MailIcon,
  BellIcon,
  MessageIcon,
  PlayIcon,
  PauseIcon,
  StopIcon,
  ClockIcon,
  CalendarIcon,
  SunIcon,
  MoonIcon,
  ChartBarIcon,
  ChartLineIcon,
  DatabaseIcon,
  TerminalIcon,
  CloudIcon,
  CaretIcon,
  LoadingDotsIcon,
} from "./set";
