// Per-category tree-shaking subpath. Re-exports a focused slice of the
// main library so consumers can `import { Icon } from "voidframe-ui/icons"`
// and drop every non-Icons component from their bundle.
//
// Source of truth: docs/taxonomy.ts Icons prefix rule (src/icons/).
//
// NOTE: explicit named re-exports rather than `export * from "../icons"`.
// vite-plugin-dts with `rollupTypes: true` produces an empty `export {}`
// for star-only barrel entries — the explicit list below is what makes
// `dist/types/icons.d.ts` populate with real declarations so TypeScript
// consumers of the `/icons` subpath get autocomplete + type-checking.
// (Report row 3 / suggestion 2.)

export { Icon, AccessibleIcon, adaptIcon, IconButton, IconGroup } from "../icons";
export type {
  IconProps,
  IconSize,
  IconButtonProps,
  IconButtonVariant,
  IconButtonSize,
  IconGroupProps,
  AccessibleIconProps,
} from "../icons";

export {
  PlusIcon,
  MinusIcon,
  CheckIcon,
  XIcon,
  EditIcon,
  TrashIcon,
  CopyIcon,
  DownloadIcon,
  UploadIcon,
  RefreshIcon,
  SaveIcon,
  ShareIcon,
  SendIcon,
  BookmarkIcon,
  PinIcon,
  ChevronUpIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  HomeIcon,
  ExternalLinkIcon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  MenuIcon,
  FileIcon,
  FileTextIcon,
  FolderIcon,
  FolderOpenIcon,
  BoldIcon,
  ItalicIcon,
  UnderlineIcon,
  CodeIcon,
  QuoteIcon,
  LinkIcon,
  InfoIcon,
  WarningIcon,
  ErrorIcon,
  SuccessIcon,
  QuestionIcon,
  SpinnerIcon,
  CircleIcon,
  SquareIcon,
  StarIcon,
  HeartIcon,
  SettingsIcon,
  UserIcon,
  UsersIcon,
  LockIcon,
  UnlockIcon,
  EyeIcon,
  EyeOffIcon,
  SearchIcon,
  FilterIcon,
  SortIcon,
  MailIcon,
  BellIcon,
  MessageIcon,
  PlayIcon,
  PauseIcon,
  StopIcon,
  ClockIcon,
  CalendarIcon,
  SunIcon,
  MoonIcon,
  ChartBarIcon,
  ChartLineIcon,
  DatabaseIcon,
  TerminalIcon,
  CloudIcon,
  CaretIcon,
  LoadingDotsIcon,
} from "../icons";
